// Generated by ReScript, PLEASE EDIT WITH CARE


function op(key, aliasesOpt, label, category, minArgs, maxArgs, argLabelsOpt) {
  let aliases = aliasesOpt !== undefined ? aliasesOpt : [];
  let argLabels = argLabelsOpt !== undefined ? argLabelsOpt : [];
  return {
    key: key,
    aliases: aliases,
    label: label,
    category: category,
    minArgs: minArgs,
    maxArgs: maxArgs,
    argLabels: argLabels
  };
}

let operators = [
  op("var", undefined, "Variable", "Path", 1, 1, ["path"]),
  op("val", undefined, "Value at path", "Path", 1, 1, ["path"]),
  op("exists", undefined, "Exists", "Path", 1, 1, ["path"]),
  op("missing", undefined, "Missing keys", "Path", 1, 1, ["keys"]),
  op("missing_some", undefined, "Missing at least N", "Path", 2, 2, [
    "min",
    "keys"
  ]),
  op("!", undefined, "Not", "Logical", 1, 1, ["value"]),
  op("!!", undefined, "To boolean", "Logical", 1, 1, ["value"]),
  op("and", undefined, "And", "Logical", 0, undefined, undefined),
  op("or", undefined, "Or", "Logical", 0, undefined, undefined),
  op("if", ["?:"], "If/Else", "Conditional", 2, undefined, [
    "condition",
    "then",
    "else"
  ]),
  op("<", undefined, "Less than", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op("<=", undefined, "Less or equal", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op(">", undefined, "Greater than", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op(">=", undefined, "Greater or equal", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op("==", undefined, "Loose equal", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op("!=", undefined, "Loose not equal", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op("===", undefined, "Strict equal", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op("!==", undefined, "Strict not equal", "Comparison", 2, undefined, [
    "left",
    "right"
  ]),
  op("+", undefined, "Add", "Arithmetic", 1, 1, ["values"]),
  op("-", undefined, "Subtract / negate", "Arithmetic", 1, 1, ["values"]),
  op("*", undefined, "Multiply", "Arithmetic", 1, 1, ["values"]),
  op("/", undefined, "Divide", "Arithmetic", 1, 1, ["values"]),
  op("%", undefined, "Modulo", "Arithmetic", 1, 1, ["values"]),
  op("min", undefined, "Min", "Arithmetic", 1, 1, ["values"]),
  op("max", undefined, "Max", "Arithmetic", 1, 1, ["values"]),
  op("map", undefined, "Map", "Iteration", 2, 2, [
    "collection",
    "callback"
  ]),
  op("filter", undefined, "Filter", "Iteration", 2, 2, [
    "collection",
    "predicate"
  ]),
  op("reduce", undefined, "Reduce", "Iteration", 3, 3, [
    "collection",
    "callback",
    "initial"
  ]),
  op("all", undefined, "All", "Iteration", 2, 2, [
    "collection",
    "predicate"
  ]),
  op("some", undefined, "Some", "Iteration", 2, 2, [
    "collection",
    "predicate"
  ]),
  op("none", undefined, "None", "Iteration", 2, 2, [
    "collection",
    "predicate"
  ]),
  op("in", undefined, "In", "Collection", 2, 2, [
    "needle",
    "haystack"
  ]),
  op("merge", undefined, "Merge", "Collection", 1, 1, ["arrays"]),
  op("throw", undefined, "Throw", "Error", 1, 1, ["payload"]),
  op("try", undefined, "Try", "Error", 1, undefined, ["attempt"]),
  op("??", undefined, "Coalesce", "Coalesce", 1, undefined, ["value"]),
  op("length", undefined, "Length", "String", 1, 1, ["value"]),
  op("cat", undefined, "Concatenate", "String", 1, 1, ["values"]),
  op("substr", undefined, "Substring", "String", 2, 3, [
    "string",
    "start",
    "length"
  ]),
  op("preserve", undefined, "Preserve raw JSON", "Literal", 1, 1, ["value"])
];

export {
  op,
  operators,
}
/* operators Not a pure module */
