// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsonLogic_Eval from "./JsonLogic_Eval.res.mjs";
import * as JsonLogic_Parse from "./JsonLogic_Parse.res.mjs";
import * as JsonLogic_Scope from "./JsonLogic_Scope.res.mjs";
import * as JsonLogic_Catalog from "./JsonLogic_Catalog.res.mjs";
import * as JsonLogic_Serialize from "./JsonLogic_Serialize.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function parse(rule) {
  return JsonLogic_Parse.parse(undefined, rule);
}

function evaluate(rule, data) {
  return JsonLogic_Eval.$$eval(undefined, rule, JsonLogic_Scope.make(data));
}

function liftParseError(e) {
  if (typeof e !== "object") {
    return "MaxDepthExceeded";
  }
  switch (e.TAG) {
    case "UnknownOperator" :
      return {
        TAG: "UnknownOperator",
        _0: e._0
      };
    case "MultiKeyObject" :
      return {
        TAG: "MultiKeyObject",
        _0: e._0
      };
    case "InvalidShape" :
      return {
        TAG: "InvalidShape",
        operator: e.operator,
        message: e.message
      };
  }
}

function liftEvalError(e) {
  if (typeof e !== "object") {
    if (e === "NaNError") {
      return "NaNError";
    } else {
      return "MaxDepthExceeded";
    }
  } else if (e.TAG === "InvalidArguments") {
    return {
      TAG: "InvalidArguments",
      _0: e._0
    };
  } else {
    return {
      TAG: "Thrown",
      _0: e._0
    };
  }
}

function apply(rule, data) {
  let e = JsonLogic_Parse.parse(undefined, rule);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: liftParseError(e._0)
    };
  }
  let v = evaluate(e._0, data);
  if (v.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: v._0
    };
  } else {
    return {
      TAG: "Error",
      _0: liftEvalError(v._0)
    };
  }
}

function liftToValidation(e) {
  if (typeof e !== "object") {
    return "MaxDepthExceeded";
  }
  switch (e.TAG) {
    case "UnknownOperator" :
      return {
        TAG: "UnknownOperator",
        _0: e._0
      };
    case "MultiKeyObject" :
      return {
        TAG: "MultiKeyObject",
        _0: e._0
      };
    case "InvalidShape" :
      return {
        TAG: "InvalidShape",
        operator: e.operator,
        message: e.message
      };
  }
}

function validate(rule) {
  let e = JsonLogic_Parse.parse(undefined, rule);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

function validateString(input) {
  let json;
  try {
    json = JSON.parse(input);
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "InvalidJson",
          _0: Stdlib_Option.getOr(Stdlib_JsExn.message(e._1), "invalid JSON")
        }
      };
    }
    throw e;
  }
  let e$1 = JsonLogic_Parse.parse(undefined, json);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: liftToValidation(e$1._0)
    };
  }
}

function isOk(r) {
  return r.TAG === "Ok";
}

function isError(r) {
  return r.TAG !== "Ok";
}

let JsonLogicError = /* @__PURE__ */Primitive_exceptions.create("JsonLogic.JsonLogicError");

function parseExn(rule) {
  let ast = JsonLogic_Parse.parse(undefined, rule);
  if (ast.TAG === "Ok") {
    return ast._0;
  }
  throw {
    RE_EXN_ID: JsonLogicError,
    _1: liftParseError(ast._0),
    Error: new Error()
  };
}

function evaluateExn(rule, data) {
  let v = evaluate(rule, data);
  if (v.TAG === "Ok") {
    return v._0;
  }
  throw {
    RE_EXN_ID: JsonLogicError,
    _1: liftEvalError(v._0),
    Error: new Error()
  };
}

function applyExn(rule, data) {
  let v = apply(rule, data);
  if (v.TAG === "Ok") {
    return v._0;
  }
  throw {
    RE_EXN_ID: JsonLogicError,
    _1: v._0,
    Error: new Error()
  };
}

function getError(caught) {
  try {
    throw caught;
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === JsonLogicError) {
      return e._1;
    } else {
      return;
    }
  }
}

let serialize = JsonLogic_Serialize.serialize;

let operators = JsonLogic_Catalog.operators;

export {
  parse,
  evaluate,
  apply,
  validate,
  validateString,
  serialize,
  operators,
  isOk,
  isError,
  JsonLogicError,
  parseExn,
  evaluateExn,
  applyExn,
  getError,
}
/* Stdlib_JsExn Not a pure module */
