// Generated by ReScript, PLEASE EDIT WITH CARE


function make(data) {
  return {
    hd: data,
    tl: /* [] */0
  };
}

function current(s) {
  if (s !== 0) {
    return s.hd;
  } else {
    return null;
  }
}

function pushOne(s, top) {
  return {
    hd: top,
    tl: s
  };
}

function pushTwo(s, top, second) {
  return {
    hd: top,
    tl: {
      hd: second,
      tl: s
    }
  };
}

function dataAt(s, n) {
  let abs = n < 0 ? -n | 0 : n;
  if (s !== 0) {
    let _remaining = s.tl;
    let _i = 1;
    let _last = s.hd;
    while (true) {
      let last = _last;
      let i = _i;
      let remaining = _remaining;
      if (remaining === 0) {
        return last;
      }
      let top = remaining.hd;
      if (i === abs) {
        return top;
      }
      _last = top;
      _i = i + 1 | 0;
      _remaining = remaining.tl;
      continue;
    };
  } else {
    return null;
  }
}

function iterMeta(i) {
  return Object.fromEntries([[
      "index",
      i
    ]]);
}

export {
  make,
  current,
  pushOne,
  pushTwo,
  dataAt,
  iterMeta,
}
/* No side effect */
