// Generated by ReScript, PLEASE EDIT WITH CARE


function noop(_args) {
  
}

let isProduction = (process.env.NODE_ENV === "production");

let log = isProduction ? noop : prim => {
    console.log(prim);
  };

let warn = isProduction ? noop : prim => {
    console.warn(prim);
  };

let error = isProduction ? noop : prim => {
    console.error(prim);
  };

let info = isProduction ? noop : prim => {
    console.info(prim);
  };

export {
  noop,
  isProduction,
  log,
  warn,
  error,
  info,
}
/* isProduction Not a pure module */
