// Generated by ReScript, PLEASE EDIT WITH CARE


function noop(_args) {
  
}

let isProduction = (process.env.NODE_ENV === "production");

let log = isProduction ? noop : prim => {
    console.log(prim);
  };

let warn = isProduction ? noop : prim => {
    console.warn(prim);
  };

let error = isProduction ? noop : prim => {
    console.error(prim);
  };

let info = isProduction ? noop : prim => {
    console.info(prim);
  };

function log$1(prim) {
  console.log(prim);
}

function warn$1(prim) {
  console.warn(prim);
}

function error$1(prim) {
  console.error(prim);
}

function info$1(prim) {
  console.info(prim);
}

let Production = {
  log: log$1,
  warn: warn$1,
  error: error$1,
  info: info$1
};

export {
  noop,
  isProduction,
  log,
  warn,
  error,
  info,
  Production,
}
/* isProduction Not a pure module */
